# automation:
  - alias: "Warn freezer door open"
    initial_state: "true"
    trigger:
      - platform: numeric_state
        entity_id: sensor.freezer_temperature
        above: 0.0
    action:
      - service: light.turn_on
        data:
          entity_id: light.living_room_left
          brightness: 255
          rgb_color: [255,0,0]

  - alias: "Freezer door closed"
    initial_state: "true"
    trigger:
      - platform: numeric_state
        entity_id: sensor.freezer_temperature
        below: -1.0
    action:
      - service: light.turn_off
        data:
          entity_id: light.living_room_left

